# Generated by Django 4.0.2 on 2022-02-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('backgrdImg', models.CharField(max_length=600)),
                ('cardImg', models.CharField(max_length=600)),
                ('description', models.CharField(max_length=1000)),
                ('subtitle', models.CharField(max_length=600)),
                ('title', models.CharField(max_length=600)),
                ('titleImg', models.CharField(max_length=600)),
                ('type', models.CharField(max_length=600)),
            ],
        ),
    ]
