# Generated by Django 4.0.2 on 2022-02-28 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DisneyApp', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='titleImg',
        ),
    ]
